### ISSUE TITLE
Some tests fail on mac

### ISSUE THREAD

**Issue by 2-complex** [TheSven73/file-objects-rs#3]
I think because temp-directories and canonicalize work differently on Mac OS (mac standard canonicalize might even be broken?)

os::canonicalize_ok_if_relative_path
os::canonicalize_ok_if_path_ends_in_dotdot
os::canonicalize_ok_if_file_exists
os::canonicalize_fails_if_subpath_is_file
os::canonicalize_ok_with_dotdot_if_paths_exist
os::remove_file_fails_if_node_is_a_directory

I'm working on a fix that dodges the idiosyncrasies of mac, but keeps the tests meaningful.

**Comment by TheSven73** [comment]
Worked with @2-complex to eliminate test failures on mac. CI queue now tests both Linux and MacOS by default.
